### ISSUE TITLE
Role to manage snapshots and create dumps using Elasticdump

### ISSUE THREAD

**Issue by sduenas** [bitergia-analytics/bitergia-analytics-opensearch#16]
The internal role `manage_snapshots' doesn't have the privileges that `elasticdump` requires to perform a dump of mappings and data. Any user mapping to this role won't be able to perform a dump.

It would be ideal to have a role that allows to do both tasks: to manage the snapshots and to allow to create dumps with `elasticdump`. 
The role can be something like:

```
bap_manage_snapshots:
  reserved: true
  hidden: false
  description: "Provide the minimum permissions for managing snapshots"
  cluster_permissions:
    - "manage_snapshots"
    - "cluster:monitor/main"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "indices:admin/create"
        - "indices:admin/mappings/get"
        - "indices:data/write/index"
```
